// Mock data for admin sections
export const mockUsers = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    avatar: "https://i.pravatar.cc/150?img=1",
    phone: "+1 (555) 123-4567",
    location: "New York, USA",
    lastLogin: "2024-03-20 10:30 AM",
    role: "user",
    status: "active",
    joinDate: "2024-01-15",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    avatar: "https://i.pravatar.cc/150?img=2",
    phone: "+1 (555) 987-6543",
    location: "Los Angeles, USA",
    lastLogin: "2024-03-19 08:15 PM",
    role: "user",
    status: "active",
    joinDate: "2024-01-20",
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob@example.com",
    avatar: "https://i.pravatar.cc/150?img=3",
    phone: "+1 (555) 222-3333",
    location: "Chicago, USA",
    lastLogin: "2024-03-18 02:45 PM",
    role: "admin",
    status: "active",
    joinDate: "2024-01-10",
  },
  {
    id: 4,
    name: "Alice Brown",
    email: "alice@example.com",
    avatar: "https://i.pravatar.cc/150?img=4",
    phone: "+1 (555) 444-5555",
    location: "Miami, USA",
    lastLogin: "2024-03-17 11:20 AM",
    role: "user",
    status: "suspended",
    joinDate: "2024-01-25",
  },
];

// Enhanced mockBookings with more fields
export const mockBookings = [
  {
    id: 1,
    user: "John Doe",
    userAvatar: "https://i.pravatar.cc/150?img=1",
    item: "Drill Set",
    itemImage:
      "https://images.pexels.com/photos/209230/pexels-photo-209230.jpeg?auto=compress&w=150",
    startDate: "2024-02-01",
    endDate: "2024-02-03",
    status: "confirmed",
    amount: 45,
    location: "New York, USA",
    createdAt: "2024-01-28",
    notes: "Handle with care.",
  },
  {
    id: 2,
    user: "Jane Smith",
    userAvatar: "https://i.pravatar.cc/150?img=2",
    item: "Ladder",
    itemImage:
      "https://images.pexels.com/photos/159220/ladders-ladder-steps-metal-159220.jpeg?auto=compress&w=150",
    startDate: "2024-02-05",
    endDate: "2024-02-07",
    status: "pending",
    amount: 30,
    location: "Los Angeles, USA",
    createdAt: "2024-02-01",
    notes: "Deliver to back entrance.",
  },
  {
    id: 3,
    user: "Bob Johnson",
    userAvatar: "https://i.pravatar.cc/150?img=3",
    item: "Power Saw",
    itemImage:
      "https://images.pexels.com/photos/209230/pexels-photo-209230.jpeg?auto=compress&w=150",
    startDate: "2024-02-10",
    endDate: "2024-02-12",
    status: "completed",
    amount: 60,
    location: "Chicago, USA",
    createdAt: "2024-02-05",
    notes: "Returned in good condition.",
  },
  {
    id: 4,
    user: "Alice Brown",
    userAvatar: "https://i.pravatar.cc/150?img=4",
    item: "Tool Kit",
    itemImage:
      "https://images.pexels.com/photos/209230/pexels-photo-209230.jpeg?auto=compress&w=150",
    startDate: "2024-02-15",
    endDate: "2024-02-17",
    status: "cancelled",
    amount: 25,
    location: "Miami, USA",
    createdAt: "2024-02-10",
    notes: "Cancelled by user.",
  },
];

// Enhanced mockItems with more fields
export const mockItems = [
  {
    id: 1,
    name: "Drill Set",
    image:
      "https://images.pexels.com/photos/209230/pexels-photo-209230.jpeg?auto=compress&w=150",
    owner: "John Doe",
    ownerAvatar: "https://i.pravatar.cc/150?img=1",
    category: "Power Tools",
    status: "active",
    price: 15,
    location: "New York, USA",
    createdAt: "2024-01-10",
    description: "High-quality drill set for all your DIY needs.",
    inventoryCount: 8,
    qualityVerified: true,
    qualityFlagged: false,
    rentalCount: 25,
  },
  {
    id: 2,
    name: "Ladder",
    image:
      "https://images.pexels.com/photos/159220/ladders-ladder-steps-metal-159220.jpeg?auto=compress&w=150",
    owner: "Jane Smith",
    ownerAvatar: "https://i.pravatar.cc/150?img=2",
    category: "Safety Equipment",
    status: "active",
    price: 10,
    location: "Los Angeles, USA",
    createdAt: "2024-01-15",
    description: "Sturdy ladder for indoor and outdoor use.",
    inventoryCount: 3,
    qualityVerified: false,
    qualityFlagged: false,
    rentalCount: 18,
  },
  {
    id: 3,
    name: "Power Saw",
    image:
      "https://images.pexels.com/photos/209230/pexels-photo-209230.jpeg?auto=compress&w=150",
    owner: "Bob Johnson",
    ownerAvatar: "https://i.pravatar.cc/150?img=3",
    category: "Power Tools",
    status: "pending",
    price: 20,
    location: "Chicago, USA",
    createdAt: "2024-01-20",
    description: "Electric power saw for precision cutting.",
    inventoryCount: 0,
    qualityVerified: false,
    qualityFlagged: true,
    rentalCount: 12,
  },
  {
    id: 4,
    name: "Tool Kit",
    image:
      "https://images.pexels.com/photos/209230/pexels-photo-209230.jpeg?auto=compress&w=150",
    owner: "Alice Brown",
    ownerAvatar: "https://i.pravatar.cc/150?img=4",
    category: "Hand Tools",
    status: "suspended",
    price: 8,
    location: "Miami, USA",
    createdAt: "2024-01-25",
    description: "Comprehensive tool kit for home repairs.",
    inventoryCount: 15,
    qualityVerified: true,
    qualityFlagged: false,
    rentalCount: 32,
  },
];

// Analytics data
export const analyticsData = {
  revenue: { current: 15420, previous: 12850, change: 20.1 },
  bookings: { current: 342, previous: 298, change: 14.8 },
  users: { current: 1247, previous: 1156, change: 7.9 },
  items: { current: 567, previous: 523, change: 8.4 },
  monthlyRevenue: [12500, 13200, 14100, 13800, 15200, 15420],
  topCategories: [
    { name: "Power Tools", revenue: 5200, bookings: 89 },
    { name: "Safety Equipment", revenue: 3800, bookings: 67 },
    { name: "Hand Tools", revenue: 2900, bookings: 45 },
    { name: "Garden Tools", revenue: 2100, bookings: 38 },
    { name: "Cleaning Tools", revenue: 1420, bookings: 23 },
  ],
  userGrowth: [156, 189, 234, 267, 298, 342],
  topLocations: [
    { city: "New York", revenue: 4200, users: 234 },
    { city: "Los Angeles", revenue: 3800, users: 198 },
    { city: "Chicago", revenue: 2900, users: 156 },
    { city: "Miami", revenue: 2100, users: 134 },
    { city: "Seattle", revenue: 1800, users: 98 },
  ],
};

// Enhanced mockMessagesSupport with more fields
export const mockMessagesSupport = [
  {
    id: 1,
    user: "John Doe",
    userAvatar: "https://i.pravatar.cc/150?img=1",
    subject: "Payment not processed",
    status: "open",
    lastMessage: "Can you check my payment?",
    lastUpdated: "2024-03-20 10:30 AM",
    messages: [
      {
        sender: "user",
        text: "Can you check my payment?",
        time: "2024-03-20 10:30 AM",
      },
      {
        sender: "admin",
        text: "We are looking into it.",
        time: "2024-03-20 11:00 AM",
      },
    ],
  },
  {
    id: 2,
    user: "Jane Smith",
    userAvatar: "https://i.pravatar.cc/150?img=2",
    subject: "App not loading",
    status: "in-progress",
    lastMessage: "Still not working on my phone.",
    lastUpdated: "2024-03-19 09:30 AM",
    messages: [
      {
        sender: "user",
        text: "App keeps crashing.",
        time: "2024-03-19 08:15 AM",
      },
      {
        sender: "admin",
        text: "What device are you using?",
        time: "2024-03-19 08:30 AM",
      },
      {
        sender: "user",
        text: "iPhone 13, iOS 17.2",
        time: "2024-03-19 09:30 AM",
      },
    ],
  },
  {
    id: 3,
    user: "Bob Johnson",
    userAvatar: "https://i.pravatar.cc/150?img=3",
    subject: "Booking issue",
    status: "resolved",
    lastMessage: "Thank you for fixing!",
    lastUpdated: "2024-03-18 02:45 PM",
    messages: [
      {
        sender: "user",
        text: "Booking not showing up.",
        time: "2024-03-18 02:00 PM",
      },
      { sender: "admin", text: "Issue resolved.", time: "2024-03-18 02:45 PM" },
    ],
  },
];

// Payment & Commissions data
export const paymentData = {
  totalRevenue: 154200,
  totalCommissions: 15420,
  pendingPayouts: 5230,
  completedPayouts: 10190,
  transactions: [
    {
      id: 1,
      user: "John Doe",
      type: "rental",
      amount: 45,
      commission: 4.5,
      status: "completed",
      date: "2024-02-15",
    },
    {
      id: 2,
      user: "Jane Smith",
      type: "rental",
      amount: 30,
      commission: 3.0,
      status: "pending",
      date: "2024-02-14",
    },
    {
      id: 3,
      user: "Bob Johnson",
      type: "rental",
      amount: 60,
      commission: 6.0,
      status: "completed",
      date: "2024-02-13",
    },
    {
      id: 4,
      user: "Alice Brown",
      type: "rental",
      amount: 25,
      commission: 2.5,
      status: "failed",
      date: "2024-02-12",
    },
    {
      id: 5,
      user: "Mike Wilson",
      type: "rental",
      amount: 80,
      commission: 8.0,
      status: "completed",
      date: "2024-02-11",
    },
  ],
  monthlyCommissions: [1200, 1350, 1420, 1380, 1520, 1542],
};

// Subscriptions data
export const subscriptionData = {
  totalSubscribers: 1247,
  activeSubscriptions: 892,
  premiumUsers: 234,
  basicUsers: 658,
  revenue: 45600,
  monthlyGrowth: 12.5,
  churnRate: 2.3,
  avgRevenuePerUser: 38.5,
  subscriptions: [
    {
      id: 1,
      user: "John Doe",
      plan: "Premium",
      amount: 29.99,
      status: "active",
      startDate: "2024-01-15",
      endDate: "2024-02-15",
      features: ["Unlimited Rentals", "Priority Support", "Insurance Coverage"],
      paymentMethod: "Credit Card",
      autoRenew: true,
    },
    {
      id: 2,
      user: "Jane Smith",
      plan: "Basic",
      amount: 9.99,
      status: "active",
      startDate: "2024-01-20",
      endDate: "2024-02-20",
      features: ["5 Rentals/Month", "Email Support"],
      paymentMethod: "PayPal",
      autoRenew: true,
    },
    {
      id: 3,
      user: "Bob Johnson",
      plan: "Premium",
      amount: 29.99,
      status: "cancelled",
      startDate: "2024-01-10",
      endDate: "2024-02-10",
      features: ["Unlimited Rentals", "Priority Support", "Insurance Coverage"],
      paymentMethod: "Credit Card",
      autoRenew: false,
    },
    {
      id: 4,
      user: "Alice Brown",
      plan: "Basic",
      amount: 9.99,
      status: "active",
      startDate: "2024-01-25",
      endDate: "2024-02-25",
      features: ["5 Rentals/Month", "Email Support"],
      paymentMethod: "Credit Card",
      autoRenew: true,
    },
    {
      id: 5,
      user: "Mike Wilson",
      plan: "Premium",
      amount: 29.99,
      status: "active",
      startDate: "2024-01-30",
      endDate: "2024-02-30",
      features: ["Unlimited Rentals", "Priority Support", "Insurance Coverage"],
      paymentMethod: "PayPal",
      autoRenew: true,
    },
    {
      id: 6,
      user: "Sarah Davis",
      plan: "Enterprise",
      amount: 99.99,
      status: "active",
      startDate: "2024-01-05",
      endDate: "2024-02-05",
      features: [
        "Unlimited Rentals",
        "Priority Support",
        "Insurance Coverage",
        "API Access",
        "Custom Branding",
      ],
      paymentMethod: "Bank Transfer",
      autoRenew: true,
    },
  ],
};

// Collateral Approvals data
export const collateralData = {
  pendingApprovals: 23,
  approvedToday: 8,
  rejectedToday: 3,
  totalApproved: 156,
  approvalRate: 87.5,
  avgProcessingTime: "2.1 hours",
  totalValue: 45600,
  approvals: [
    {
      id: 1,
      user: "John Doe",
      item: "Drill Set",
      value: 150,
      type: "Power Tools",
      status: "pending",
      submittedDate: "2024-02-15",
      collateralType: "Equipment",
      description: "Professional grade drill set with multiple attachments",
      images: ["drill1.jpg", "drill2.jpg"],
      documents: ["receipt.pdf", "warranty.pdf"],
      verificationStatus: "pending",
      riskScore: "low",
    },
    {
      id: 2,
      user: "Jane Smith",
      item: "Ladder",
      value: 80,
      type: "Safety Equipment",
      status: "approved",
      submittedDate: "2024-02-14",
      collateralType: "Equipment",
      description: "Aluminum extension ladder, 16ft height",
      images: ["ladder1.jpg"],
      documents: ["receipt.pdf"],
      verificationStatus: "verified",
      riskScore: "low",
    },
    {
      id: 3,
      user: "Bob Johnson",
      item: "Power Saw",
      value: 200,
      type: "Power Tools",
      status: "rejected",
      submittedDate: "2024-02-13",
      collateralType: "Equipment",
      description: "Circular saw with safety features",
      images: ["saw1.jpg"],
      documents: ["receipt.pdf"],
      verificationStatus: "failed",
      riskScore: "medium",
      rejectionReason: "Document verification failed",
    },
    {
      id: 4,
      user: "Alice Brown",
      item: "Tool Kit",
      value: 120,
      type: "Hand Tools",
      status: "pending",
      submittedDate: "2024-02-12",
      collateralType: "Equipment",
      description: "Complete hand tool set with case",
      images: ["tools1.jpg", "tools2.jpg"],
      documents: ["receipt.pdf"],
      verificationStatus: "pending",
      riskScore: "low",
    },
    {
      id: 5,
      user: "Mike Wilson",
      item: "Garden Tools",
      value: 95,
      type: "Garden Tools",
      status: "approved",
      submittedDate: "2024-02-11",
      collateralType: "Equipment",
      description: "Professional garden tool set",
      images: ["garden1.jpg"],
      documents: ["receipt.pdf"],
      verificationStatus: "verified",
      riskScore: "low",
    },
    {
      id: 6,
      user: "Sarah Davis",
      item: "Government ID",
      value: 0,
      type: "Identity Verification",
      status: "pending",
      submittedDate: "2024-02-10",
      collateralType: "Document",
      description: "Driver's license for identity verification",
      images: ["id_front.jpg", "id_back.jpg"],
      documents: [],
      verificationStatus: "pending",
      riskScore: "low",
    },
    {
      id: 7,
      user: "David Lee",
      item: "Security Deposit",
      value: 500,
      type: "Financial",
      status: "approved",
      submittedDate: "2024-02-09",
      collateralType: "Financial",
      description: "Cash security deposit for high-value rentals",
      images: [],
      documents: ["bank_statement.pdf"],
      verificationStatus: "verified",
      riskScore: "low",
    },
  ],
};

// Reports & Disputes data
export const reportsData = {
  totalReports: 45,
  openDisputes: 12,
  resolvedToday: 8,
  averageResolutionTime: "2.3 days",
  satisfactionRate: 94.2,
  escalationRate: 8.5,
  reports: [
    {
      id: 1,
      reporter: "John Doe",
      reportedUser: "Jane Smith",
      reason: "Item not as described",
      status: "open",
      priority: "high",
      date: "2024-02-15",
      category: "Item Quality",
      description:
        "The drill set was missing several attachments that were listed in the description",
      evidence: ["photo1.jpg", "photo2.jpg"],
      requestedAction: "Refund",
      assignedTo: "Admin Team",
      lastUpdated: "2024-02-15 14:30",
    },
    {
      id: 2,
      reporter: "Bob Johnson",
      reportedUser: "Alice Brown",
      reason: "Late delivery",
      status: "in-progress",
      priority: "medium",
      date: "2024-02-14",
      category: "Service",
      description: "Item was delivered 2 hours after the agreed time",
      evidence: ["screenshot1.jpg"],
      requestedAction: "Partial Refund",
      assignedTo: "Support Team",
      lastUpdated: "2024-02-14 16:45",
    },
    {
      id: 3,
      reporter: "Mike Wilson",
      reportedUser: "Sarah Davis",
      reason: "Damaged item",
      status: "resolved",
      priority: "high",
      date: "2024-02-13",
      category: "Item Damage",
      description: "Ladder arrived with bent rungs and safety concerns",
      evidence: ["damage1.jpg", "damage2.jpg"],
      requestedAction: "Full Refund",
      assignedTo: "Admin Team",
      lastUpdated: "2024-02-13 11:20",
      resolution: "Full refund issued, item removed from platform",
    },
    {
      id: 4,
      reporter: "Emily Chen",
      reportedUser: "David Lee",
      reason: "No-show",
      status: "open",
      priority: "low",
      date: "2024-02-12",
      category: "Service",
      description: "Renter did not show up for scheduled pickup",
      evidence: ["message1.jpg"],
      requestedAction: "Compensation",
      assignedTo: "Support Team",
      lastUpdated: "2024-02-12 09:15",
    },
    {
      id: 5,
      reporter: "Lisa Wang",
      reportedUser: "Tom Harris",
      reason: "Payment issue",
      status: "resolved",
      priority: "medium",
      date: "2024-02-11",
      category: "Payment",
      description: "Double charge on credit card for single rental",
      evidence: ["statement1.jpg"],
      requestedAction: "Refund",
      assignedTo: "Finance Team",
      lastUpdated: "2024-02-11 13:40",
      resolution: "Refund processed, apology sent",
    },
    {
      id: 6,
      reporter: "Alex Rodriguez",
      reportedUser: "Maria Garcia",
      reason: "Inappropriate behavior",
      status: "open",
      priority: "high",
      date: "2024-02-10",
      category: "Conduct",
      description: "Renter made inappropriate comments during pickup",
      evidence: ["message2.jpg"],
      requestedAction: "Account Suspension",
      assignedTo: "Admin Team",
      lastUpdated: "2024-02-10 17:30",
    },
  ],
};

// Platform Settings data
export const settingsData = {
  general: {
    platformName: "RentSmart",
    contactEmail: "support@rentsmart.com",
    supportPhone: "+1 234 567 890",
    timezone: "UTC-5",
    currency: "USD",
    language: "English",
    maintenanceMode: false,
    registrationEnabled: true,
    emailNotifications: true,
    smsNotifications: false,
  },
  fees: {
    platformFee: 10,
    transactionFee: 2.9,
    minimumPayout: 50,
    lateFee: 5,
    cancellationFee: 3,
    insuranceFee: 2,
  },
  security: {
    twoFactorAuth: true,
    sessionTimeout: 24,
    maxLoginAttempts: 5,
    passwordMinLength: 8,
    requireStrongPasswords: true,
    ipWhitelist: [],
    apiRateLimit: 1000,
    dataEncryption: true,
  },
  appearance: {
    theme: "dark",
    primaryColor: "#10b981",
    accentColor: "#3b82f6",
    logoUrl: "/logo.png",
    faviconUrl: "/favicon.ico",
    customCSS: "",
  },
  notifications: {
    emailAlerts: true,
    smsAlerts: false,
    pushNotifications: true,
    marketingEmails: false,
    systemUpdates: true,
    securityAlerts: true,
  },
  integrations: {
    stripeEnabled: true,
    paypalEnabled: true,
    googleAnalytics: true,
    facebookPixel: false,
    slackWebhook: "",
    zapierEnabled: false,
  },
};